"""
    types.py\n
    List of cuisine types to suggest to a searching user.
"""

# NOTE: do not change unless a new location type is inserted into the `restaurants` collection.
EE_TYPES = [
    "Cocktail Bars",
    "New American",
    "Gastropubs",
    "Latin American",
    "Italian",
    "Korean",
    "Noodles",
    "Breakfast & Brunch",
    "French",
    "Pizza",
    "Barbeque",
    "Seafood",
    "Comfort Food",
    "Bars",
    "Tapas/Small Plates",
    "Vegetarian",
    "Wine Bars",
    "Asian Fusion",
    "Beer, Wine & Spirits",
    "Chinese",
    "Mexican",
    "Chicken Shop",
    "Soup",
    "Steakhouses",
    "Lounges",
    "Vegan",
    "Caribbean",
    "Mediterranean",
    "Sandwiches",
    "Pubs",
    "Ramen",
    "Delis",
    "Thai",
    "Live/Raw Food",
    "Japanese",
    "Middle Eastern",
    "Bakeries",
    "Cafes",
    "Dim Sum",
    "African",
    "American",
    "Burgers",
    "Acai Bowls",
    "Bubble Tea",
    "Taiwanese",
    "Gluten-Free",
    "Hot Pot",
    "Sushi Bars",
    "Brasseries",
    "Sports Bars",
    "Hawaiian",
    "Soul Food",
    "Tacos",
    "Specialty Food",
    "Beer Bar",
    "Izakaya",
    "Halal",
    "Moroccan",
    "Hong Kong Style Cafe",
    "Filipino",
    "Southern",
    "Food Stands",
    "Vietnamese",
    "Salad",
    "Wraps",
    "Smokehouse",
    "Indian",
    "Venues & Event Spaces",
    "Cantonese",
    "Diners",
    "Tex-Mex",
    "Desserts",
    "Coffee & Tea",
    "Juice Bars & Smoothies",
    "Tapas Bars",
    "Peruvian",
    "Buffets",
    "Kebab",
    "Argentine",
    "Hookah Bars",
    "Caterers",
    "Modern European",
    "Cajun/Creole",
    "Armenian",
    "Lebanese",
    "Food Trucks",
    "Brazilian",
    "Creperies",
    "Indonesian",
    "Art Museums",
    "Cultural Center",
    "Pop-Up Restaurants",
    "Persian/Iranian",
    "Cuban",
    "Karaoke",
    "Hot Dogs",
    "Organic Stores",
    "Laotian",
    "New Mexican Cuisine",
    "Patisserie/Cake Shop",
    "Speakeasies",
    "Himalayan/Nepalese",
    "Teppanyaki",
    "Cannabis Collective",
    "Cannabis Dispensaries",
    "Restaurants",
    "Performing Arts",
    "Pasta Shops",
    "Falafel",
    "Cheese Shops",
    "Ethiopian",
    "Chicken Wings",
    "Mongolian",
    "German",
    "Food Delivery Services",
    "Scandinavian",
    "Empanadas",
    "Greek",
    "Syrian",
    "Bagels",
    "Street Vendors",
    "Waffles",
    "Supper Clubs",
    "Belgian",
    "Cheesesteaks",
    "Tiki Bars",
    "Cooking Classes",
    "Fast Food",
    "Kosher",
    "British",
    "Ice Cream & Frozen Yogurt",
    "Malaysian",
    "Singaporean",
    "Shaved Ice",
    "Pan Asian",
    "Salvadoran",
    "Japanese Curry",
    "Georgian",
    "Colombian",
    "Pakistani",
    "Music Venues",
    "Dance Clubs",
    "Spanish",
    "Bangladeshi",
    "Arcades",
    "Farmers Market",
    "Poke",
    "Food Court",
    "Donuts",
    "Dive Bars",
    "Art Galleries",
    "Pancakes",
    "Whiskey Bars",
    "Burmese",
    "Grocery",
    "Jazz & Blues"
]
